apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: simple-app-ui-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: simple-app-ui
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 3
